[project]
name = "vts_bridge"
version = "0.1.0"
description = "A python library for interacting with the VTube Studio API without asyncio"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "websockets",
    "numpy",
    "pyvts>=0.3.3",
    "loop_rate_limiters",
]
